export const siteConfig = {
  title: "My Next.js Starter",
  description: "A fully optimized Next.js 15 starter template.",
  url: process.env.NEXT_PUBLIC_URL || "https://yourwebsite.com",
  siteName: "My Next.js Starter",
  keywords: ["Next.js", "Tailwind CSS", "SEO", "TypeScript"],
  ogImage: "/og-image.png",
  logo: "/logo.png",
}
export const siteNAP = {
  name: "Your Company Name",
  googleBusinessType: "ProfessionalService" as const,
  contact: "John Does",
  contactTitle: "CEO",
  email: "example@gmail.com",
  phone: "+1123456789",
  address: "123 Street",
  city: "City",
  state: "State",
  zipCode: "12345",
  openingHours: "Mon-Fri 9am-5pm",
  socialMedia: {
    facebook: "https://facebook.com/yourpage",
    twitter: "https://twitter.com/yourprofile",
    instagram: "https://instagram.com/yourprofile",
    linkedin: "https://linkedin.com/in/yourprofile",
    youtube: "https://youtube.com/yourchannel",
  },
  logo: "/logo.png",
  favicon: "/favicon.ico",
  images: ["business-image.png"],
}
