name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Auto-cancel older runs on the same branch / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04 # pin image for consistent native binaries
    timeout-minutes: 60
    env:
      NEXT_TELEMETRY_DISABLED: "1" # silence Next.js telemetry banner

    steps:
      - uses: actions/checkout@v4

      # Node + built-in npm cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20 # Playwright ≥1.44 requires ≥18
          cache: npm

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false

      # Cache Playwright’s browser bundle (~100 MB)
      - name: Cache Playwright browsers
        id: pw-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-pw-1 # bump the number when Playwright major changes

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # ── Next.js build cache ────────────────────────────────────────────────
      - name: Restore Next.js build cache
        id: next-cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Build Next.js app
        run: npm run build

      - name: Save Next.js build cache
        if: steps.next-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ steps.next-cache.outputs.cache-primary-key }}

      # ── Tests ─────────────────────────────────────────────────────────────
      - name: Run Playwright tests
        run: npm run test

      # ── Upload HTML report (optional) ─────────────────────────────────────
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
