name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    env:
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_ENV: "production"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --no-audit --progress=false

      # ── Patch the Mac-only lockfile: fetch Linux native binaries ──
      - name: Rebuild native deps for Linux
        run: |
          npm rebuild sharp lightningcss @tailwindcss/oxide

      - name: Build Next.js app
        run: npm run build

      - name: Echo
        run: echo "Hello, world!"
